# Explore Dataset

This notebook is meant to be a workspace to look at stuff
***

***
## Config + Reading + Vars
***

In [1]:
import pandas as pd
from pathlib import Path
import numpy as np

SAMPLE_DATA_PARQUET_PATH = Path.cwd().parent / "data" / "posts-sample.parquet"

CLUSTER_DIR = Path.cwd().parent / "data" / "clusters"
CANONICAL_CLUSTER_DIR = CLUSTER_DIR / "canonical"
ARTIST_AVG_FAV_COUNT_CLUSTER = CANONICAL_CLUSTER_DIR / "artist_avg_fav_count" / "labels.npy"

DANBOORU_ITEM_MAPPING = Path.cwd().parent / "data" / "danbooru_eda" / "danbooru_item_mapping.npy"
DOMAIN_POST_IDS_PATH = Path.cwd().parent / "data" / "danbooru_eda" / "domain_post_ids.npy"

EMBEDDINGS_PATH = Path("/home/main/Desktop/files/projects/hycompass/data/danbooru_input_v1/embeddings.npy")

In [2]:
## Load data
sample_df = pd.read_parquet(SAMPLE_DATA_PARQUET_PATH)  ## Needs pandas, pyarrow upgraded python -m pip install --upgrade pandas pyarrow
artist_avg_fav_count = np.load(ARTIST_AVG_FAV_COUNT_CLUSTER)
# danbooru_item_mapping = np.load(DANBOORU_ITEM_MAPPING)
danbooru_domain_post_ids = np.load(DOMAIN_POST_IDS_PATH)

In [3]:
sample_df.columns

Index(['id', 'created_at', 'uploader_id', 'score', 'source', 'md5',
       'last_comment_bumped_at', 'rating', 'image_width', 'image_height',
       'tag_string', 'fav_count', 'file_ext', 'last_noted_at', 'parent_id',
       'has_children', 'approver_id', 'tag_count_general', 'tag_count_artist',
       'tag_count_character', 'tag_count_copyright', 'file_size', 'up_score',
       'down_score', 'is_pending', 'is_flagged', 'is_deleted', 'tag_count',
       'updated_at', 'is_banned', 'pixiv_id', 'last_commented_at',
       'has_active_children', 'bit_flags', 'tag_count_meta', 'has_large',
       'has_visible_children', 'media_asset', 'tag_string_general',
       'tag_string_character', 'tag_string_copyright', 'tag_string_artist',
       'tag_string_meta', 'file_url', 'large_file_url', 'preview_file_url'],
      dtype='str')

In [4]:
with pd.option_context("display.max_columns", None):
    display(sample_df.head())

,id,created_at,uploader_id,score,source,md5,last_comment_bumped_at,rating,image_width,image_height,tag_string,fav_count,file_ext,last_noted_at,parent_id,has_children,approver_id,tag_count_general,tag_count_artist,tag_count_character,tag_count_copyright,file_size,up_score,down_score,is_pending,is_flagged,is_deleted,tag_count,updated_at,is_banned,pixiv_id,last_commented_at,has_active_children,bit_flags,tag_count_meta,has_large,has_visible_children,media_asset,tag_string_general,tag_string_character,tag_string_copyright,tag_string_artist,tag_string_meta,file_url,large_file_url,preview_file_url
0,1,2005-05-24 03:35:31+00:00,1.0,2725,http://www.biwa.ne.jp/~kyogoku/nekotama.jpg,d34e4cf0a437a5d65f8e82b7bcd02606,NaT,s,459,650,1girl 2000s_(style) :p ;p animal_ear_fluff ani...,2854,jpg,NaT,57501.0,False,NaN,63,1,1,2,127238,2719,-10,False,False,False,70,2026-06-10 02:14:22.259000+00:00,False,NaN,2025-09-22 10:27:05.421000+00:00,False,0.0,3,False,False,"{'id': None, 'created_at': None, 'updated_at':...",1girl 2000s_(style) :p ;p animal_ear_fluff ani...,kousaka_tamaki,to_heart_(series) to_heart_2,kyogoku_shin,bad_id bad_link commentary,https://cdn.donmai.us/original/d3/4e/d34e4cf0a...,https://cdn.donmai.us/original/d3/4e/d34e4cf0a...,https://cdn.donmai.us/180x180/d3/4e/d34e4cf0a4...
1,2,2005-05-24 03:37:30+00:00,1.0,50,http://page.freett.com/tyuyan/leafkey_014658.png,710fd9cba4ef37260f9152ffa9d154d8,NaT,s,450,450,2000s_(style) 2boys 2girls ahoge ass bad_id ba...,60,png,NaT,NaN,False,109167.0,49,1,7,6,232601,59,-8,False,False,False,66,2026-03-03 17:46:01.448000+00:00,False,NaN,2024-11-07 15:29:35.723000+00:00,False,0.0,3,False,False,"{'id': None, 'created_at': None, 'updated_at':...",2000s_(style) 2boys 2girls ahoge ass blue_hair...,card_master_peach haga_reiko kuhonbutsu_taishi...,cardcaptor_sakura comic_party leaf_(studio) to...,nakamura_hisashi,bad_id bad_link lowres,https://cdn.donmai.us/original/71/0f/710fd9cba...,https://cdn.donmai.us/original/71/0f/710fd9cba...,https://cdn.donmai.us/180x180/71/0f/710fd9cba4...
2,3,2005-05-24 03:38:05+00:00,1.0,101,http://page.freett.com/tyuyan/saber%20top.jpg,fdb47f79fb8da82e66eeb1d84a1cae8d,NaT,g,444,621,1girl 2000s_(style) 2005 ahoge armor armored_d...,131,jpg,NaT,NaN,False,NaN,45,1,2,2,190709,102,-3,False,False,False,52,2026-06-15 13:52:56.315000+00:00,False,NaN,2025-05-23 14:30:45.023000+00:00,False,0.0,2,False,False,"{'id': None, 'created_at': None, 'updated_at':...",1girl 2000s_(style) 2005 ahoge armor armored_d...,artoria_pendragon_(fate) saber_(fate),fate/stay_night fate_(series),nakamura_hisashi,bad_id translated,https://cdn.donmai.us/original/fd/b4/fdb47f79f...,https://cdn.donmai.us/original/fd/b4/fdb47f79f...,https://cdn.donmai.us/180x180/fd/b4/fdb47f79fb...
3,4,2005-05-24 03:42:26+00:00,1.0,51,https://ja.hentai-img.com/image/48-pictures-ma...,552e74406af8a2b6b8b7fd547bc2c353,NaT,s,600,730,2000s_(style) 2girls :d ;) arm_up armpits bare...,70,jpg,NaT,NaN,False,NaN,45,1,2,1,122693,53,-1,False,False,False,49,2026-05-14 04:40:17.974000+00:00,False,NaN,2024-06-04 15:13:48.674000+00:00,False,0.0,0,False,False,"{'id': None, 'created_at': None, 'updated_at':...",2000s_(style) 2girls :d ;) arm_up armpits bare...,sugiura_midori tokiha_mai,my-hime,soshina_nohito,,https://cdn.donmai.us/original/55/2e/552e74406...,https://cdn.donmai.us/original/55/2e/552e74406...,https://cdn.donmai.us/180x180/55/2e/552e74406a...
4,5,2005-05-24 03:57:53+00:00,1.0,110,http://4040.main.jp/noteimage/20050523.jpg,4f5ac0caa62550b0eeac5d91a9f53ffe,NaT,q,512,384,2000s_(style) 3girls :d ass bad_id bamboo_fenc...,211,jpg,NaT,NaN,False,NaN,46,1,3,1,62853,110,-1,False,False,False,52,2026-05-14 04:40:58.339000+00:00,False,NaN,2025-01-18 19:07:17.428000+00:00,False,0.0,1,False,False,"{'id': None, 'created_at': None, 'updated_at':...",2000s_(style) 3girls :d ass bamboo_fence baref...,kojima_kirie koyomi_hare_nanaka miharu_sena_ka...,girls_bravo,sanshita,bad_id,https://cdn.donmai.us/original/4f/5a/4f5ac0caa...,https://cdn.donmai.us/original/4f/5a/4f5ac0caa...,https://cdn.donmai.us/180x180/4f/5a/4f5ac0caa6...

In [5]:
# def get_cluster_label_for_post_id(post_id, domain_post_ids, cluster_labels):
#     mapping_indices = np.where(danbooru_domain_post_ids == post_id)

#     if len(mapping_indices[0]) > 1:
#         return 0
#     elif len(mapping_indices[0]) == 0:
#         return 0
#     else:
#         mapping_index = mapping_indices[0][0]
#         # print(f"Post ID: {post_id}, Mapping Index: {mapping_index}")

#     cluster_label = cluster_labels[mapping_index]
#     return cluster_label

In [6]:
# ## Try to populate sample df with artist_avg_fav_count cluster labels
# sample_df["artist_avg_fav_count_cluster"] = sample_df["id"].apply(
#     lambda post_id: get_cluster_label_for_post_id(
#         post_id=post_id,
#         domain_post_ids=danbooru_domain_post_ids,
#         cluster_labels=artist_avg_fav_count
#     )
# )

In [7]:
# Build the lookup once
domain_index = pd.Index(danbooru_domain_post_ids.astype(str))
positions = domain_index.get_indexer(sample_df["id"].astype(str))
valid = positions >= 0

# Add all cluster files as columns
for path in CANONICAL_CLUSTER_DIR.glob("*/labels.npy"):
    labels = np.load(path)

    result = np.zeros(len(sample_df), dtype=labels.dtype)
    result[valid] = labels[positions[valid]]

    sample_df[f"{path.parent.name}_cluster"] = result

In [8]:
# Memory-map the 30 GB file (doesn't load everything)
embeddings = np.load(EMBEDDINGS_PATH, mmap_mode="r")

# Retrieve only embeddings corresponding to sample posts
sample_embeddings = np.full(
    (len(sample_df), embeddings.shape[1]),
    np.nan,
    dtype=np.float32
)

sample_embeddings[valid] = embeddings[positions[valid]]

# Add embeddings to DataFrame
sample_df["embedding"] = list(sample_embeddings)

In [9]:
with pd.option_context("display.max_columns", None):
    display(sample_df.head())

,id,created_at,uploader_id,score,source,md5,last_comment_bumped_at,rating,image_width,image_height,tag_string,fav_count,file_ext,last_noted_at,parent_id,has_children,approver_id,tag_count_general,tag_count_artist,tag_count_character,tag_count_copyright,file_size,up_score,down_score,is_pending,is_flagged,is_deleted,tag_count,updated_at,is_banned,pixiv_id,last_commented_at,has_active_children,bit_flags,tag_count_meta,has_large,has_visible_children,media_asset,tag_string_general,tag_string_character,tag_string_copyright,tag_string_artist,tag_string_meta,file_url,large_file_url,preview_file_url,created_at_year_cluster,is_pending_cluster,copyright_median_score_cluster,up_score_bin_cluster,character_avg_fav_count_cluster,is_banned_cluster,down_score_bin_cluster,copyright_total_fav_count_cluster,is_deleted_cluster,character_total_score_cluster,score_bin_cluster,file_size_bin_cluster,tag_count_copyright_bin_cluster,megapixels_bin_cluster,character_avg_score_cluster,tag_count_character_bin_cluster,copyright_avg_score_cluster,copyright_median_fav_count_cluster,tag_count_general_bin_cluster,character_total_fav_count_cluster,image_width_bin_cluster,rating_combination_cluster,artist_median_score_cluster,source_domain_major_cluster,character_median_fav_count_cluster,character_median_score_cluster,artist_avg_fav_count_cluster,artist_avg_score_cluster,updated_at_year_cluster,copyright_avg_fav_count_cluster,last_commented_at_year_cluster,artist_total_score_cluster,copyright_total_score_cluster,fav_count_bin_cluster,created_at_age_band_cluster,tag_count_meta_bin_cluster,tag_count_artist_bin_cluster,last_comment_bumped_at_year_cluster,tag_count_bin_cluster,aspect_ratio_bin_cluster,is_flagged_cluster,artist_total_fav_count_cluster,file_ext_major_cluster,image_height_bin_cluster,artist_median_fav_count_cluster,last_noted_at_year_cluster,embedding
0,1,2005-05-24 03:35:31+00:00,1.0,2725,http://www.biwa.ne.jp/~kyogoku/nekotama.jpg,d34e4cf0a437a5d65f8e82b7bcd02606,NaT,s,459,650,1girl 2000s_(style) :p ;p animal_ear_fluff ani...,2854,jpg,NaT,57501.0,False,NaN,63,1,1,2,127238,2719,-10,False,False,False,70,2026-06-10 02:14:22.259000+00:00,False,NaN,2025-09-22 10:27:05.421000+00:00,False,0.0,3,False,False,"{'id': None, 'created_at': None, 'updated_at':...",1girl 2000s_(style) :p ;p animal_ear_fluff ani...,kousaka_tamaki,to_heart_(series) to_heart_2,kyogoku_shin,bad_id bad_link commentary,https://cdn.donmai.us/original/d3/4e/d34e4cf0a...,https://cdn.donmai.us/original/d3/4e/d34e4cf0a...,https://cdn.donmai.us/180x180/d3/4e/d34e4cf0a4...,1,0,1,9,3,0,3,1,0,2,10,2,3,1,1,2,1,1,7,2,1,8,3,0,2,1,3,3,21,1,21,4,1,10,8,4,2,0,7,1,0,4,1,2,3,0,"[0.17053166, 0.16761795, -1.2567654, 0.6379773..."
1,2,2005-05-24 03:37:30+00:00,1.0,50,http://page.freett.com/tyuyan/leafkey_014658.png,710fd9cba4ef37260f9152ffa9d154d8,NaT,s,450,450,2000s_(style) 2boys 2girls ahoge ass bad_id ba...,60,png,NaT,NaN,False,109167.0,49,1,7,6,232601,59,-8,False,False,False,66,2026-03-03 17:46:01.448000+00:00,False,NaN,2024-11-07 15:29:35.723000+00:00,False,0.0,3,False,False,"{'id': None, 'created_at': None, 'updated_at':...",2000s_(style) 2boys 2girls ahoge ass blue_hair...,card_master_peach haga_reiko kuhonbutsu_taishi...,cardcaptor_sakura comic_party leaf_(studio) to...,nakamura_hisashi,bad_id bad_link lowres,https://cdn.donmai.us/original/71/0f/710fd9cba...,https://cdn.donmai.us/original/71/0f/710fd9cba...,https://cdn.donmai.us/180x180/71/0f/710fd9cba4...,1,0,1,6,2,0,4,1,0,1,6,2,6,1,1,6,1,1,6,1,1,8,1,0,2,1,2,2,21,1,20,1,1,7,8,4,2,0,7,2,0,1,2,1,1,0,"[-0.44989887, 0.5005186, -0.34814805, 0.156846..."
2,3,2005-05-24 03:38:05+00:00,1.0,101,http://page.freett.com/tyuyan/saber%20top.jpg,fdb47f79fb8da82e66eeb1d84a1cae8d,NaT,g,444,621,1girl 2000s_(style) 2005 ahoge armor armored_d...,131,jpg,NaT,NaN,False,NaN,45,1,2,2,190709,102,-3,False,False,False,52,2026-06-15 13:52:56.315000+00:00,False,NaN,2025-05-23 14:30:45.023000+00:00,False,0.0,2,False,False,"{'id': None, 'created_at': None, 'updated_at':...",1girl 2000s_(style) 2005 ahoge armor armored_d...,artoria_pendragon_(fate) saber_(fate),fate/stay_night fate_(series),nakamura_hisashi,bad_id translated,https://cdn.donmai.us/original/fd/b4/fdb47f79f...,https://cdn.donmai.us/original/fd/b4/fdb47f79f...,https://cdn.donmai.us/180x180/fd/b4/fdb47f79fb...,1,0,3,7,4,0,5,3,0,5,8,2,3,1,3,3,3,4,6,5,1,4,1,0,3,3,2,2,21,4,21,1,3,8,8,3,2,0,7,1,0,1,1,2,1,0,"[0.52775747, 0.4296654, -1.3096944, 0.26471213..."
3,4,2005-05-24 03:42:26+00:00,1.0,51,https://ja.hentai-img.com/image/48-pictures-ma...,552e74406af8a2b6b8b7fd547bc2c353,NaT,s,600,730,2000s_(style) 2girls :d ;) arm_up armpits bare...,70,jpg,NaT,NaN,False,NaN,45,1,2,1,122693,53,-1,False,False,False,49,2026-05-14 04:40:17.974000+00:00,False,NaN,2024-06-04 15:13:48.674000+00:00,False,0.0,0,False,False,"{'id': None, 'created_at': None, 'updated_at':...",2000s_(style) 2girls :d ;) arm_up armpits bare...,sugiura_midori tokiha_mai,my-hime,soshina_nohito,,https://cdn.donmai.us/original/55/2e/552e74406...,https://cdn.donmai.us/original/55/2e/552e74406...,https://cdn.donmai.us/180x180/55/2e/552e74406a...,1,0,1,6,2,0,5,1,0,1,7,2,2,1,1,3,1,1,6,1,2,8,1,0,2,1,1,1,21,1,20,1,1,7,8,1,2,0,6,2,0,1,1,2,1,0,"[-0.2786931, -0.025211094, -1.8153205, 0.20962..."
4,5,2005-05-24 03:57:53+00:00,1.0,110,http://4040.main.jp/noteimage/20050523.jpg,4f5ac0caa62550b0eeac5d91a9f53ffe,NaT,q,512,384,2000s_(style) 3girls :d ass bad_id bamboo_fenc...,211,jpg,NaT,NaN,False,NaN,46,1,3,1,62853,110,-1,False,False,False,52,2026-05-14 04:40:58.339000+00:00,False,NaN,2025-01-18 19:07:17.428000+00:00,False,0.0,1,False,False,"{'id': None, 'created_at': None, 'updated_at':...",2000s_(style) 3girls :d ass bamboo_fence baref...,kojima_kirie koyomi_hare_nanaka miharu_sena_ka...,girls_bravo,sanshita,bad_id,https://cdn.donmai.us/original/4f/5a/4f5ac0caa...,https://cdn.donmai.us/original/4f/5a/4f5ac0caa...,https://cdn.donmai.us/180x180/4f/5a/4f5ac0caa6...,1,0,2,7,3,0,5,1,0,1,8,1,2,1,2,4,1,3,6,1,1,2,2,0,3,2,3,2,21,3,21,3,1,8,8,2,2,0,7,3,0,3,1,1,3,0,"[0.8128828, 0.054870874, 0.4607699, 0.30381212..."

In [10]:
## Save populated sample_df to parquet
POPULATED_SAMPLE_DATA_PARQUET_PATH = Path.cwd().parent / "data" / "posts-sample-populated.parquet"
sample_df.to_parquet(POPULATED_SAMPLE_DATA_PARQUET_PATH, index=False)